export const Constant = {
	BASE_URL: "",
	CATEGORY: "categories",
	SUBCATEGORY: "subcategories",
	TEST: "tests",
	VIDEO: "videos",
	EBOOK: "ebooks",
	QUESTION: "questions",
	BANNER: "banners",
	HEADERCOLOR: "#def6f8",
	COMPLETEDTEST: "#ebfad1",
	TABCLICK: "#a1c4c8",
	MISSEDTEST: "#fde1dd",
	NEETPG: "#0688d4",
	MBBSPROF: "#ea5b0c",
	FMGE: "#e9940f",
	CONTACT: "#d80fd7",
	QUICKQUERY: "#3157a2",
	SUBSCRIPTION1: "#25aae3",
	SUBSCRIPTION2: "#2490bf",
	FREE: "#38a50a",
}